<?php

return [
    [
        'company' => 'Advantis Global',
        'start_date' => strtotime('9/1/2020'),
        'end_data' => null,
        'title' => 'Software Engineer II contracted to Facebook',
        'skills' => [
            [ 'technology' => 'Hack (strongly-typed PHP)', 'version' => '4' ],
            [ 'technology' => 'PHPUnit' ],
            [ 'technology' => 'React' ],
            [ 'technology' => 'Object-oriented programming' ],
        ],
        'accomplishments' => [
            'Migrated video metrics from sunsetted system to new, more performant statistics engine',
            'Improved test suite with more thorough and consistent coverage using computationally-generated test cases',
        ],
    ],
    [
        'company' => 'Sporcle',
        'start_date' => strtotime('11/1/2018'),
        'end_date' => strtotime('1/1/2020'),
        'title' => 'Web and Salesforce Developer',
        'skills' => [
            [ 'technology' => 'PHP', 'version' => '7.2' ],
            [ 'technology' => 'HTML', 'version' => '5' ],
            [ 'technology' => 'CSS', 'version' => '3' ],
            [ 'technology' => 'Salesforce Apex', ],
            [ 'technology' => 'SOQL', ],
            [ 'technology' => 'Redis', 'version' => '5' ],
            [ 'technology' => 'Lightning Design Components', ],
            [ 'technology' => 'Salesforce custom objects', ],
            [ 'technology' => 'VisualForce' ],
            [ 'technology' => 'REST API', ],
            [ 'technology' => 'SVG', ],
            [ 'technology' => 'Responsive web design', ],
        ],
        'accomplishments' => [
            'Maintained the world\'s largest trivia site',
            'Created new desktop and mobile versions of website footer, the first step of a major site redesign',
            'Enhanced forms and pages on the Sporcle Live host portal',
            'Added new features that improved the sales team\'s external communications and reduced workload',
            'Spearheaded growth of Salesforce Apex automated test suite from 600 to 2600 tests in ten months',
        ],
    ],
    [
        'company' => 'Salesforce',
        'start_date' => strtotime('1/1/2016'),
        'end_date' => strtotime('11/1/2018'),
        'title' => 'Software Engineer',
        'skills' => [
            [ 'technology' => 'PHP', 'version' => '7.1' ],
            [ 'technology' => 'PHPUnit' ],
            [ 'technology' => 'Symfony', 'version' => '1' ],
            [ 'technology' => 'Salesforce Apex', ],
            [ 'technology' => 'SOQL', ],
            [ 'technology' => 'Object-oriented programming' ],
            [ 'technology' => 'Github' ],
            [ 'technology' => 'Ant', ],
            [ 'technology' => 'Agile methodology' ],
        ],
        'accomplishments' => [
            'Developed and maintained Pardot, a marketing automation platform',
            'Created presentation database used in public launch of Wave Analytics (now B2B Marketing Analytics)',
            'Maintained connector, used to synchronize data between Pardot and Salesforce',
            'Authored over 40 pull requests, reviewed over 170 pull requests, and tested over 50 pull requests',
            'Named Pardot MVP in November 2017 for innovations introduced as team scrum master',
        ],
    ],
    [
        'company' => 'LAMP Camp / The Cresca Group',
        'start_date' => strtotime('7/1/2015'),
        'end_date' => strtotime('10/1/2015'),
        'title' => 'LAMP Stack Developer',
        'skills' => [
            [ 'technology' => 'PHP', 'version' => '5.5' ],
            [ 'technology' => 'MySQL', 'version' => '5.6' ],
            [ 'technology' => 'HTML', 'version' => '4' ],
            [ 'technology' => 'jQuery', 'version' => '2' ],
            [ 'technology' => 'MVC architecture' ],
            [ 'technology' => 'Git' ],
            [ 'technology' => 'PSR autoloading' ],
        ],
        'accomplishments' => [
            'Finished program of study and earned certificate of completion',
            'Designed and developed an inventory and sales tracking system',
            'In lead developer role, served as a coding and testing knowledge resource for new developers',
            'Created data visualization objects'
        ],
    ],
    [
        'company' => 'Sterling BackCheck',
        'start_date' => strtotime('11/1/2014'),
        'end_date' => strtotime('7/1/2015'),
        'title' => 'Software Engineer Consultant',
        'skills' => [
            [ 'technology' => 'Delphi', 'version' => '7' ],
            [ 'technology' => 'C#' ],
            [ 'technology' => 'Microsoft SQL Server' ],
            [ 'technology' => 'SOAP' ],
            [ 'technology' => 'Word OLE' ],
        ],
        'accomplishments' => [
            'Maintained a suite of applications used to retrieve and report background check information',
            'Developed contextual date parser, improving recognition rate by a factor of 10',
            'Diagnosed and repaired issues involving SOAP communication security and Word OLE',
        ],
    ],
    [
        'company' => 'Well Played, LLC',
        'start_date' => strtotime('9/1/2012'),
        'end_date' => strtotime('7/1/2015'),
        'title' => 'Owner',
        'skills' => [
            [ 'technology' => 'PHP', 'version' => '5.3' ],
            [ 'technology' => 'Lazarus (Open-source Delphi)', 'version' => '1.2' ],
            [ 'technology' => 'MySQL', 'version' => '5.5' ],
            [ 'technology' => 'Amazon Marketplace Web Services API' ],
            [ 'technology' => 'Square Connect API' ],
        ],
        'accomplishments' => [
            'Co-founded a board and card game retail business with sales revenue of over $35,000 in 2014',
            'Authored an inventory system',
            'Created and automated services to post products for sale and to download financial transactions from point-of-sale system',
            'Excelled in teaching dozens of new games to hundreds of enthusiasts at events and conventions throughout the Southeast',
        ],
    ],
    [
        'company' => 'ADP Incorporated',
        'start_date' => strtotime('8/1/2007'),
        'end_date' => strtotime('5/1/2012'),
        'title' => 'Senior Software Analyst',
        'skills' => [
            [ 'technology' => 'Delphi', 'version' => '2007' ],
            [ 'technology' => 'Oracle', 'version' => '10g' ],
            [ 'technology' => 'Crystal Reports', 'version' => '9.0' ],
        ],
        'accomplishments' => [
            'Designed, developed, and maintained a flexible spending account management database',
            'Coordinated with other business units to author and maintain several stand-alone applications that import data and generate reports',
            'Created development estimates, design documents, unit tests, and user acceptance testing outlines',
        ],
    ],
    [
        'company' => 'Young Consulting',
        'start_date' => strtotime('9/1/2006'),
        'end_date' => strtotime('8/1/2007'),
        'title' => 'Software Analyst',
        'skills' => [
            [ 'technology' => 'Delphi', 'version' => '6.0' ],
            [ 'technology' => 'QuickReports' ],
            [ 'technology' => 'Microsoft Reporting Services' ],
        ],
        'accomplishments' => [
            'Maintained an insurance proposal and claims application suite',
            'Created and maintained auto-generated reports',
        ],
    ],
    [
        'company' => 'BellSouth',
        'start_date' => strtotime('7/1/2004'),
        'end_date' => strtotime('9/1/2006'),
        'title' => 'Systems Analyst II',
        'skills' => [
            [ 'technology' => 'Delphi', 'version' => '6.0' ],
        ],
        'accomplishments' => [
            'Developed and maintained a quote generation application',
            'In technical lead analyst role, oversaw the day-to-day operations of a team of three developers',
            'In post-implementation lead analyst role, coordinated and managed repair of defect backlog',
            'Authored over 100 analysis, specification, and unit test documents',
            'Developed standard document templates for group use',
        ],
    ],
    [
        'company' => 'CCH Incorporated',
        'title' => 'Programmer Analyst',
        'start_date' => strtotime('10/1/2002'),
        'end_date' => strtotime('6/1/2004'),
        'skills' => [
            [ 'technology' => 'Delphi', 'version' => '7.0' ],
            [ 'technology' => 'Crystal Reports', 'version' => '9.0' ],
        ],
        'accomplishments' => [
            'Analyzed, developed and maintained a suite of accounting practice management software',
            'Acted as a resource for Crystal Reports expertise for multiple divisions and locations of the company',
        ],
    ],
    [
        'company' => 'Artisan Software Design',
        'title' => 'Owner',
        'start_date' => strtotime('8/1/2001'),
        'end_date' => strtotime('10/1/2002'),
        'accomplishments' => [
            'Founded and managed a freelance software consulting practice',
        ],
    ],
    [
        'company' => 'Columbia Ultimate Business Systems',
        'title' => 'Delphi Developer',
        'start_date' => strtotime('9/1/2000'),
        'end_date' => strtotime('8/1/2001'),

    ],
    [
        'company' => 'ClickChoice.com',
        'title' => 'Developer',
        'start_date' => strtotime('7/1/1999'),
        'end_date' => strtotime('8/1/2000'),
        'accomplishments' => [
            'Developed and maintained home internet filtering software',
        ],
    ],
    [
        'company' => 'Computing Solutions',
        'title' => 'Associate Developer',
        'start_date' => strtotime('6/1/1996'),
        'end_date' => strtotime('7/1/1999'),
        'accomplishments' => [
            'Designed and developed custom software for multiple small business clients',
        ],
    ],
];
